// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: current_user.proto

package music_platform

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrentUserService_GetCurrentUserProfile_FullMethodName = "/current_user.CurrentUserService/GetCurrentUserProfile"
)

// CurrentUserServiceClient is the client API for CurrentUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrentUserServiceClient interface {
	GetCurrentUserProfile(ctx context.Context, in *GetCurrentUserProfileRequest, opts ...grpc.CallOption) (*GetCurrentUserProfileResponse, error)
}

type currentUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrentUserServiceClient(cc grpc.ClientConnInterface) CurrentUserServiceClient {
	return &currentUserServiceClient{cc}
}

func (c *currentUserServiceClient) GetCurrentUserProfile(ctx context.Context, in *GetCurrentUserProfileRequest, opts ...grpc.CallOption) (*GetCurrentUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentUserProfileResponse)
	err := c.cc.Invoke(ctx, CurrentUserService_GetCurrentUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrentUserServiceServer is the server API for CurrentUserService service.
// All implementations must embed UnimplementedCurrentUserServiceServer
// for forward compatibility.
type CurrentUserServiceServer interface {
	GetCurrentUserProfile(context.Context, *GetCurrentUserProfileRequest) (*GetCurrentUserProfileResponse, error)
	mustEmbedUnimplementedCurrentUserServiceServer()
}

// UnimplementedCurrentUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrentUserServiceServer struct{}

func (UnimplementedCurrentUserServiceServer) GetCurrentUserProfile(context.Context, *GetCurrentUserProfileRequest) (*GetCurrentUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentUserProfile not implemented")
}
func (UnimplementedCurrentUserServiceServer) mustEmbedUnimplementedCurrentUserServiceServer() {}
func (UnimplementedCurrentUserServiceServer) testEmbeddedByValue()                            {}

// UnsafeCurrentUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrentUserServiceServer will
// result in compilation errors.
type UnsafeCurrentUserServiceServer interface {
	mustEmbedUnimplementedCurrentUserServiceServer()
}

func RegisterCurrentUserServiceServer(s grpc.ServiceRegistrar, srv CurrentUserServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrentUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrentUserService_ServiceDesc, srv)
}

func _CurrentUserService_GetCurrentUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).GetCurrentUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrentUserService_GetCurrentUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).GetCurrentUserProfile(ctx, req.(*GetCurrentUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrentUserService_ServiceDesc is the grpc.ServiceDesc for CurrentUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrentUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "current_user.CurrentUserService",
	HandlerType: (*CurrentUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentUserProfile",
			Handler:    _CurrentUserService_GetCurrentUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "current_user.proto",
}
