// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: current_user.proto

package music_platform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserProfileRequest) Reset() {
	*x = GetCurrentUserProfileRequest{}
	mi := &file_current_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserProfileRequest) ProtoMessage() {}

func (x *GetCurrentUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_current_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_current_user_proto_rawDescGZIP(), []int{0}
}

type GetCurrentUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserProfileResponse) Reset() {
	*x = GetCurrentUserProfileResponse{}
	mi := &file_current_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserProfileResponse) ProtoMessage() {}

func (x *GetCurrentUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_current_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_current_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentUserProfileResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCurrentUserProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCurrentUserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_current_user_proto protoreflect.FileDescriptor

const file_current_user_proto_rawDesc = "" +
	"\n" +
	"\x12current_user.proto\x12\fcurrent_user\"\x1e\n" +
	"\x1cGetCurrentUserProfileRequest\"Y\n" +
	"\x1dGetCurrentUserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email2\x86\x01\n" +
	"\x12CurrentUserService\x12p\n" +
	"\x15GetCurrentUserProfile\x12*.current_user.GetCurrentUserProfileRequest\x1a+.current_user.GetCurrentUserProfileResponseB\x12Z\x10./music_platformb\x06proto3"

var (
	file_current_user_proto_rawDescOnce sync.Once
	file_current_user_proto_rawDescData []byte
)

func file_current_user_proto_rawDescGZIP() []byte {
	file_current_user_proto_rawDescOnce.Do(func() {
		file_current_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_current_user_proto_rawDesc), len(file_current_user_proto_rawDesc)))
	})
	return file_current_user_proto_rawDescData
}

var file_current_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_current_user_proto_goTypes = []any{
	(*GetCurrentUserProfileRequest)(nil),  // 0: current_user.GetCurrentUserProfileRequest
	(*GetCurrentUserProfileResponse)(nil), // 1: current_user.GetCurrentUserProfileResponse
}
var file_current_user_proto_depIdxs = []int32{
	0, // 0: current_user.CurrentUserService.GetCurrentUserProfile:input_type -> current_user.GetCurrentUserProfileRequest
	1, // 1: current_user.CurrentUserService.GetCurrentUserProfile:output_type -> current_user.GetCurrentUserProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_current_user_proto_init() }
func file_current_user_proto_init() {
	if File_current_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_current_user_proto_rawDesc), len(file_current_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_current_user_proto_goTypes,
		DependencyIndexes: file_current_user_proto_depIdxs,
		MessageInfos:      file_current_user_proto_msgTypes,
	}.Build()
	File_current_user_proto = out.File
	file_current_user_proto_goTypes = nil
	file_current_user_proto_depIdxs = nil
}
